notifications:
  slack:
    secure: 1FyBgBaSwA2v29ZzQTMFINRL6Gruk7Hc7nBZUoHQrFbE5X8FdPCP627Z4NNxFeqlTAhbn7GsjMquSlD/5m9OZgIzy9HZ89cJx4W930xDWMm4xmpxWtJtjbENy/91WmEA2HZCYMt+DS7C6xqT55kDBRWBGBnAplpFD5TE7QZzrJIDNqqbPOHXmXyBj1wHwtE0fS1sxlnZBMnJPkRqcGOVpkBR5MzGGzY9CyemaJsYKpwu7a+bszn5o4T1RfqGXEUiCp6KlKO0ceeAk7dmNwL+65t09wOdyqUCsA5ipsnAWDMhXOQci9k27UYfdXSNBjxqYr1ehcm7XIf8hxzXdFgt2Rk+xOxG9bhX8hQ5QltRWqjk8f3ykeBPAI0wNqfGXpYAck07BNPkssR5nzg/2p96ViyHo080knlNxlXHcsyHQs6qxtYmQz97CXWO+RiHRhbJHITf4UInDswXSXXDk5eCgsIrdGVATq3qwAsGVCHD+v+WfO05uS1AYRF7hq52BirupRi4RIpKWvXh+/CZziIVKCDui3jDEEsqsZY7iNN3QL35yOl6p0PQBL+1BkEWrjTwb1J/zNtDKpfdfbh41YYlrRMsKMEd9lT6Sz3r7dEYWyRR4bln4UBQISLowv4jbWNsRth+b4KP73QPGsHejJ/1z4EG8pjryJeG1cpBn/kF+ks=
language: go
go:
- 1.8
- tip
matrix:
  allow_failures:
  - go: tip
before_install:
- go get -v golang.org/x/lint/golint
- go get -v golang.org/x/tools/cmd/cover

install:
- go get -v -d -t ./...
