notifications:
  slack:
    secure: 1FyBgBaSwA2v29ZzQTMFINRL6Gruk7Hc7nBZUoHQrFbE5X8FdPCP627Z4NNxFeqlTAhbn7GsjMquSlD/5m9OZgIzy9HZ89cJx4W930xDWMm4xmpxWtJtjbENy/91WmEA2HZCYMt+DS7C6xqT55kDBRWBGBnAplpFD5TE7QZzrJIDNqqbPOHXmXyBj1wHwtE0fS1sxlnZBMnJPkRqcGOVpkBR5MzGGzY9CyemaJsYKpwu7a+bszn5o4T1RfqGXEUiCp6KlKO0ceeAk7dmNwL+65t09wOdyqUCsA5ipsnAWDMhXOQci9k27UYfdXSNBjxqYr1ehcm7XIf8hxzXdFgt2Rk+xOxG9bhX8hQ5QltRWqjk8f3ykeBPAI0wNqfGXpYAck07BNPkssR5nzg/2p96ViyHo080knlNxlXHcsyHQs6qxtYmQz97CXWO+RiHRhbJHITf4UInDswXSXXDk5eCgsIrdGVATq3qwAsGVCHD+v+WfO05uS1AYRF7hq52BirupRi4RIpKWvXh+/CZziIVKCDui3jDEEsqsZY7iNN3QL35yOl6p0PQBL+1BkEWrjTwb1J/zNtDKpfdfbh41YYlrRMsKMEd9lT6Sz3r7dEYWyRR4bln4UBQISLowv4jbWNsRth+b4KP73QPGsHejJ/1z4EG8pjryJeG1cpBn/kF+ks=
language: go
go:
- 1.6
matrix:
  allow_failures:
  - go: tip
before_install:
- go get -v github.com/golang/lint/golint
- go get -v golang.org/x/tools/cmd/cover
- go get -v github.com/mattn/goveralls
install:
- go get -v -d -t ./...

#Not working yet need to figure out coveralls
# script: - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken=$COVERALLS_TOKEN
# env:
#   global:
#     secure: oiLH1pxHenuC+SSEjAPxje3AOZR8PsT1Pafv1M4fqb0vnzQnIHB3hmunaBBPsjmjc/wc3Dnx/MiUMZQO8oO7HAtKnCAC7LmX/ajFo35rllVGU6aJytAXG0SjmpdlNhIm6aCu8zjb4clrzJNjWn/NPsAo1b9I7GNtUmgWOmhBhjWNjX6Ddk0+85BZySqS+4Di/Sv5+T1lzJwTl8b4JECaqsrzPgT38tDruQ3LPPaweFQQvuZoQJPs5HmHebCHxe7TcFnBo1lT51LG0dmKOvsFIBDjeKUQ/y1cyai5O4A+bMQ4EsNWWZxlZ/kPuScbENLKK1/R/bDVA+lsZwkKv/6FL/fNZABuVY7A2J/PickFXGtXp1+L0UDmK7MNvFYulM2yTF1ivp6ihOe8So2m5c2KZyA0/UOloqcjC+4Nb069/GReiIRLOS6Dn5tLO2eWjp0HslVYfvh61v75K/tK3Lw0ZvXw1FMKXUCnhJQ1/2XwmIf80dvUYKiGVVbiMBaaQADbO+hKsh8464iea7GB38jXL4KNLe6IZ3fYSq6Oz+7/9DPjMD2DuQ4/PI37rjgIIo+1eiTtbjKOy3B3wOYNpcvdiw4o4WmgA+QhI1jsnTLKehkrdgjhupCji0syHE54Mt0n+e0ZWoggjQ4n9pQVPLQGbyxiG7eZUtcnz9Sw8Z7Kh34=
